import type { IMegaMenu } from '../models/MegaMenu'

export const defaultRoutesMegaMenu: IMegaMenu = {
  menu_key: 'routes',
  title: 'Tuyến Đi Tỉnh 2 Chiều',
  banner_top: {
    title: 'Thuê Xe Riêng Đi Tỉnh 2 Chiều & Sân Bay',
    subtitle: 'Đón trả tận nhà · Giá trọn gói minh bạch · Phục vụ 24/7',
    cta_text: 'Xem cam kết dịch vụ',
    cta_link: '/#dich-vu',
  },
  columns: [
    {
      column_id: 'col-airport',
      title: 'Đưa Đón Sân Bay',
      icon: 'i-lucide-plane',
      order: 1,
      items: [
        {
          title: 'Sân bay TSN ⇄ Vũng Tàu',
          description: 'Cao tốc Long Thành êm ái',
          link: '/xe-rieng-vung-tau-di-san-bay-tan-son-nhat',
          item_type: 'route',
          order: 1,
          is_active: true,
        },
      ],
    },
    {
      column_id: 'col-east',
      title: 'Miền Đông & Du Lịch',
      icon: 'i-lucide-palmtree',
      order: 2,
      items: [
        {
          title: 'Sài Gòn ⇄ Vũng Tàu / Hồ Tràm',
          description: 'Đón trả tận resort & khách sạn',
          link: '/xe-rieng-tphcm-di-vung-tau',
          item_type: 'route',
          order: 1,
          is_active: true,
        },
        {
          title: 'Sài Gòn ⇄ Đồng Nai',
          description: 'Biên Hòa, Long Khánh, KCN',
          link: '/xe-rieng-tphcm-di-dong-nai',
          item_type: 'route',
          order: 2,
          is_active: true,
        },
        {
          title: 'Sài Gòn ⇄ Tây Ninh',
          description: 'Núi Bà Đen, Tòa Thánh',
          link: '/xe-rieng-tphcm-di-tay-ninh',
          item_type: 'route',
          order: 3,
          is_active: true,
        },
        {
          title: 'Sài Gòn ⇄ Lâm Đồng (Đà Lạt)',
          description: 'Du lịch nghỉ dưỡng phố núi',
          link: '/xe-rieng-tphcm-di-da-lat',
          item_type: 'route',
          order: 4,
          is_active: true,
        },
        {
          title: 'Sài Gòn ⇄ Khánh Hòa (Nha Trang)',
          description: 'Cao tốc Bắc Nam liền mạch',
          link: '/xe-rieng-tphcm-di-nha-trang',
          item_type: 'route',
          order: 5,
          is_active: true,
        },
      ],
    },
    {
      column_id: 'col-west',
      title: 'Miền Tây (ĐBSCL)',
      icon: 'i-lucide-waves',
      order: 3,
      items: [
        {
          title: 'Sài Gòn ⇄ Cần Thơ',
          description: 'Thủ phủ miền Tây Nam Bộ',
          link: '/xe-rieng-tphcm-di-can-tho',
          item_type: 'route',
          order: 1,
          is_active: true,
        },
        {
          title: 'Sài Gòn ⇄ An Giang',
          description: 'Châu Đốc, Miếu Bà Chúa Xứ',
          link: '/xe-rieng-tphcm-di-an-giang',
          item_type: 'route',
          order: 2,
          is_active: true,
        },
        {
          title: 'Sài Gòn ⇄ Đồng Tháp',
          description: 'Cao Lãnh, Làng hoa Sa Đéc',
          link: '/xe-rieng-tphcm-di-dong-thap',
          item_type: 'route',
          order: 3,
          is_active: true,
        },
        {
          title: 'Sài Gòn ⇄ Vĩnh Long',
          description: 'Cầu Mỹ Thuận 2 nhanh chóng',
          link: '/xe-rieng-tphcm-di-vinh-long',
          item_type: 'route',
          order: 4,
          is_active: true,
        },
        {
          title: 'Sài Gòn ⇄ Cà Mau',
          description: 'Đất Mũi, trọn gói khứ hồi',
          link: '/xe-rieng-tphcm-di-ca-mau',
          item_type: 'route',
          order: 5,
          is_active: true,
        },
      ],
    },
    {
      column_id: 'col-highlands',
      title: 'Tây Nguyên',
      icon: 'i-lucide-mountain-snow',
      order: 4,
      items: [
        {
          title: 'Sài Gòn ⇄ Đắk Lắk',
          description: 'Buôn Ma Thuột thủ phủ cà phê',
          link: '/xe-rieng-tphcm-di-dak-lak',
          item_type: 'route',
          order: 1,
          is_active: true,
        },
        {
          title: 'Sài Gòn ⇄ Gia Lai',
          description: 'Pleiku, Biển Hồ phố núi',
          link: '/xe-rieng-tphcm-di-gia-lai',
          item_type: 'route',
          order: 2,
          is_active: true,
        },
      ],
    },
  ],
  footer_bar: {
    items: ['Bao trọn xe 100%', 'Đón đúng giờ hẹn', '0đ phụ phí ẩn'],
    hotline: '0972 97 0000',
  },
  is_active: true,
}
