name: Deploy

on:
  push:
    branches:
      - test
      - production

jobs:
  deploy-test:
    if: github.ref == 'refs/heads/test'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Test
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}

          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

            export NODE_OPTIONS="--max-old-space-size=4096"

            cd /var/www/test

            git fetch origin
            git checkout test
            git reset --hard origin/test

            set -a
            [ -f .env ] && source .env
            set +a

            npm install
            npm run build

            pm2 delete test-happytrip-3000 2>/dev/null || true
            PORT=3000 pm2 start .output/server/index.mjs --name test-happytrip-3000 -i 1

  deploy-production:
    if: github.ref == 'refs/heads/production'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Production
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}

          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

            export NODE_OPTIONS="--max-old-space-size=4096"

            cd /var/www/product

            git fetch origin
            git checkout production
            git reset --hard origin/production

            set -a
            [ -f .env ] && source .env
            set +a

            npm install
            npm run build

            pm2 delete production-app-8888 2>/dev/null || true
            PORT=8888 pm2 start .output/server/index.mjs --name production-app-8888 -i 1